//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string UserGame { get; set; }
        public string Password { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Points { get; set; }
        public string TypeUser { get; set; }
        public Nullable<int> Ingreso { get; set; }
    }
}
