USE [master]
GO

/****** Object:  Database [Directorio]    Script Date: 05/04/2019 10:58:14 ******/
CREATE DATABASE [Directorio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Directorio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Directorio.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Directorio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Directorio_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Directorio] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Directorio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Directorio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Directorio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Directorio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Directorio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Directorio] SET ARITHABORT OFF 
GO

ALTER DATABASE [Directorio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Directorio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Directorio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Directorio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Directorio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Directorio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Directorio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Directorio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Directorio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Directorio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Directorio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Directorio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Directorio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Directorio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Directorio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Directorio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Directorio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Directorio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Directorio] SET  MULTI_USER 
GO

ALTER DATABASE [Directorio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Directorio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Directorio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Directorio] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Directorio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Directorio] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Directorio] SET  READ_WRITE 
GO

